backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "aktuality"
    label: "Aktuality"
    folder: "content/aktuality"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }
